language: go
go:
- master

git:
  depth: 1


notifications:
  email: false

script: 
  - go test -v -race ./test/...
  - go test ./test/benchmark -bench . -benchmem
  - go test -v -race ./AmeCache/...